### ISSUE TITLE
CHADTree works also when it is unused

### ISSUE THREAD

**Issue by przepompownia** [ms-jpq/chadtree#131]
I noticed that chadtree working after 
- `Invalid window id` error occurred (after running FZF or vimspector).
- htop reported that it still works and consumes CPU in an unexplained way

**Comment by ms-jpq** [comment]
can you please try again, i think point 2. is fixed.

point 1. has an issue here https://github.com/ms-jpq/chadtree/issues/105

hopefully i can fix it without some major rewrite

thanks :)

**Comment by przepompownia** [comment]
Before looking how the changes works I would like to save myself from running `CHADdeps` on each update by creating a git hook that does the same.

I suspect that probably I have to run `python3 -m pip install --upgrade --requirement requirements.txt` from the top chadtree dir. After executing it I still get the prompt to run `CHADdeps`. 

Another thing: the following requirements
```
git+https://github.com/ms-jpq/std2.git@a42443ea6de414a846a75a704feba6d06fa04146
git+https://github.com/ms-jpq/pynvim_pp.git@52ad6dc45be8bd1e6407c6d38d46da041e5d2b43
```
forces `git` to clone the whole repository even if nothing changed from the previous run. 

The version using archive
```
https://github.com/ms-jpq/std2/archive/a42443ea6de414a846a75a704feba6d06fa04146.tar.gz
https://github.com/ms-jpq/pynvim_pp/archive/52ad6dc45be8bd1e6407c6d38d46da041e5d2b43.tar.gz
```
works and is faster (and cache is used):
```
 chadtree [chad] $ python3 -m pip install --upgrade --requirement requirements.txt 
Collecting https://github.com/ms-jpq/std2/archive/a42443ea6de414a846a75a704feba6d06fa04146.tar.gz (from -r requirements.txt (line 3))
  Using cached https://github.com/ms-jpq/std2/archive/a42443ea6de414a846a75a704feba6d06fa04146.tar.gz
Collecting https://github.com/ms-jpq/pynvim_pp/archive/52ad6dc45be8bd1e6407c6d38d46da041e5d2b43.tar.gz (from -r requirements.txt (line 4))
  Using cached https://github.com/ms-jpq/pynvim_pp/archive/52ad6dc45be8bd1e6407c6d38d46da041e5d2b43.tar.gz
```

https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/#installing-via-tarballs

**Comment by przepompownia** [comment]
```
...
Error detected while processing function CHADon_stderr:
line    1:
Traceback (most recent call last):
Error detected while processing function CHADon_stderr:
line    1:
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.vim/pack/bundle/opt/chadtree/chadtree/__main__.py", line 53, in <module>
    EnvBuilder(
  File "/usr/lib/python3.9/venv/__init__.py", line 75, in create
    self._setup_pip(context)
  File "/usr/lib/python3.9/venv/__init__.py", line 303, in _setup_pip
    subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 40] Too many levels of symbolic links: '/home/user/.vim/pack/bundle/opt/chadtree/.vars/runtime/bin/python3'
Error detected while processing function CHADon_exit:
line    1:
 | CHADTree EXITED - 1
```
The second running `CHADdeps`:
```
...
Collecting https://github.com/ms-jpq/std2/archive/a42443ea6de414a846a75a704feba6d06fa04146.tar.gz (from -r /home/user/.vim/pack/bundle/opt/chadtree/requirements.txt (line 3))
ERROR: Could not install packages due to an EnvironmentError: Missing dependencies for SOCKS support.

Error detected while processing function CHADon_stderr:
line    1:
Installation failed, check :message
Error detected while processing function CHADon_exit:
line    1:
 | CHADTree EXITED - 1
```
I get the same error when I try to clone deps in the old way. 

My `pip` is configured to used SOCKS. 
```
 $ cat ~/.config/pip/pip.conf 
[global]
        proxy = socks5h://127.0.0.1:9050
```
It worked before upgrading chadtree to the fresh master. 

It looks like problem with import. I discovered it after unmuting exception messages:
```python
    try:
        import pynvim
        import pynvim_pp
        import std2
        import yaml
    except ImportError as msg:
        print(msg, end="", file=stderr)
        exit(1)
    except RuntimeError as msg:
        print(msg, end="", file=stderr)
        exit(1)
```
and got
```
No module named 'pynvim' | CHADTree EXITED - 1 
```
which is false. Probably it cannot import pysocks module in the same way.

**Comment by przepompownia** [comment]
`:pyx import pynvim,vim, sys, socks,std2, pynvim_pp, yaml; print(sys.version)` executed as vim command works without errors.

**Comment by ms-jpq** [comment]
@przepompownia 

Actually CHADTree works like [pipx](https://pipxproject.github.io/pipx/)

It uses a private virtual environment, to isolate itself from everything else. It's the only solution that works reliability, because unfortunately python has pretty crap package management.

To reduce unnecessary installs I need to implement a lock file, which I removed because I just wanted to push windows support out, but it should be next on the list.

I had to change the package management because pip didnt allow `--target` if you installed python from the microsoft store

**Comment by przepompownia** [comment]
Now chadtree is unable to start for me because modules are unavailable from its very restricted environment.

**Comment by ms-jpq** [comment]
Humm interesting, can you please undo whatever you did and try again?

Maybe `PYTHONHOME` was set? That would conflict with `venv`, so I should add a rule that removes it.

It should work then because it works [under Docker](https://github.com/ms-jpq/chadtree/blob/chad/docker/Dockerfile), and thats about as restrictive as you can make it

**Comment by przepompownia** [comment]
The same - after `git stash` on chadtree repository and `rm -rf __pycache__/ .vars`. `PYTHONHOME` is not set.

**Comment by ngocthienvnn** [comment]
Had the same problems after the upgrading. I had to reinstall but it din't work, then I made it works by doing some commands;
1. sudo apt-get install python3-venv
2. Goto Chadtree folder and run this command: python3 -m chadtree deps  
p/s: Im on Kubuntu 20.10/ Neovim v0.5.0-dev+1048

**Comment by przepompownia** [comment]
>     2. Goto Chadtree folder and run this command: python3 -m chadtree deps

It works (also without cloning whole repos) and make chadtree usable again for me, assumming fetching without SOCKS. 

@ms-jpq please 
- allow use pysock in pipx environment
- make modules available when running from vim
- use archived github packages to avoid cloning repos each time

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/203/files
I added code for killing itself when parent process id changes
